// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScrumMaster.Api.Data;

#nullable disable

namespace ScrumMaster.Api.Data.Migrations
{
    [DbContext(typeof(ScrumMasterDbContext))]
    [Migration("20260816130457_AddPollUtilite")]
    partial class AddPollUtilite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iteration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxVotesParParticipant")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath");

                    b.HasIndex("ThemeId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Colonne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Colonnes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Equipe", b =>
                {
                    b.Property<string>("AreaPath")
                        .HasColumnType("text");

                    b.Property<string>("TeamsChannelId")
                        .HasColumnType("text");

                    b.HasKey("AreaPath");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DateCloture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeReunion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath", "TypeReunion", "Date")
                        .IsUnique();

                    b.ToTable("PollsUtilite");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColonneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuteurParticipantId");

                    b.HasIndex("BoardId");

                    b.HasIndex("ColonneId");

                    b.ToTable("PostIts");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstParDefaut")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstPredefini")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Vote", b =>
                {
                    b.Property<Guid>("PostItId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("PostItId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.VoteUtilite", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamsUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateVote")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reponse")
                        .HasColumnType("integer");

                    b.HasKey("PollId", "TeamsUserId");

                    b.ToTable("VotesUtilite");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithMany("Boards")
                        .HasForeignKey("AreaPath")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Colonne", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Theme", "Theme")
                        .WithMany("Colonnes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Participant", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Board", "Board")
                        .WithMany("Participants")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("AreaPath")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Participant", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Board", "Board")
                        .WithMany("PostIts")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Colonne", "Colonne")
                        .WithMany()
                        .HasForeignKey("ColonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Board");

                    b.Navigation("Colonne");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Vote", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.PostIt", "PostIt")
                        .WithMany("Votes")
                        .HasForeignKey("PostItId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("PostIt");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.VoteUtilite", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.PollUtilite", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("PostIts");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Equipe", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Theme", b =>
                {
                    b.Navigation("Colonnes");
                });
#pragma warning restore 612, 618
        }
    }
}
