// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScrumMaster.Api.Data;

#nullable disable

namespace ScrumMaster.Api.Data.Migrations
{
    [DbContext(typeof(ScrumMasterDbContext))]
    [Migration("20260817194753_AddColonneVisuelHabillage")]
    partial class AddColonneVisuelHabillage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Iteration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxVotesParParticipant")
                        .HasColumnType("integer");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Colonne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Couleur")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<string>("UrlIllustration")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ThemeId");

                    b.ToTable("Colonnes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ConfigurationAzureDevOps", b =>
                {
                    b.Property<string>("AreaPath")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateConfiguration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PatChiffre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Projet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AreaPath");

                    b.ToTable("ConfigurationsAzureDevOps");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Equipe", b =>
                {
                    b.Property<string>("AreaPath")
                        .HasColumnType("text");

                    b.Property<string>("TeamsChannelId")
                        .HasColumnType("text");

                    b.HasKey("AreaPath");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Etape", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MiniJeuCatalogueId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ThemeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MiniJeuCatalogueId");

                    b.HasIndex("ThemeId");

                    b.HasIndex("BoardId", "Ordre")
                        .IsUnique();

                    b.ToTable("Etapes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.MiniJeuCatalogue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeInterne")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TypeInterne")
                        .IsUnique();

                    b.ToTable("MiniJeuxCatalogue");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.OptionPollPersonnalise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EtapeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtapeId");

                    b.ToTable("OptionsPollPersonnalise");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("DateCloture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int>("TypeReunion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath", "TypeReunion", "Date")
                        .IsUnique();

                    b.ToTable("PollsUtilite");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuteurParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColonneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EtapeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("WorkItemExporteId")
                        .HasColumnType("integer");

                    b.Property<int?>("WorkItemSourceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuteurParticipantId");

                    b.HasIndex("ColonneId");

                    b.HasIndex("EtapeId");

                    b.ToTable("PostIts");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.RappelEnvoye", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AreaPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("DateEnvoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TypeReunion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath", "TypeReunion", "Date")
                        .IsUnique();

                    b.ToTable("RappelsEnvoyes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ReponseMeteoEquipe", b =>
                {
                    b.Property<Guid>("EtapeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateReponse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Humeur")
                        .HasColumnType("integer");

                    b.HasKey("EtapeId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ReponsesMeteoEquipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ReponsePollPersonnalise", b =>
                {
                    b.Property<Guid>("EtapeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DateReponse")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.HasKey("EtapeId", "ParticipantId");

                    b.HasIndex("OptionId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ReponsesPollPersonnalise");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Theme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contexte")
                        .HasColumnType("text");

                    b.Property<bool>("EstParDefaut")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstPredefini")
                        .HasColumnType("boolean");

                    b.Property<string>("Icone")
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Vote", b =>
                {
                    b.Property<Guid>("PostItId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.HasKey("PostItId", "ParticipantId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.VoteUtilite", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uuid");

                    b.Property<string>("TeamsUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateVote")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomAffiche")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Reponse")
                        .HasColumnType("integer");

                    b.HasKey("PollId", "TeamsUserId");

                    b.ToTable("VotesUtilite");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithMany("Boards")
                        .HasForeignKey("AreaPath")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Colonne", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Theme", "Theme")
                        .WithMany("Colonnes")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ConfigurationAzureDevOps", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithOne()
                        .HasForeignKey("ScrumMaster.Api.Models.ConfigurationAzureDevOps", "AreaPath")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Etape", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Board", "Board")
                        .WithMany("Etapes")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.MiniJeuCatalogue", "MiniJeuCatalogue")
                        .WithMany()
                        .HasForeignKey("MiniJeuCatalogueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ScrumMaster.Api.Models.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Board");

                    b.Navigation("MiniJeuCatalogue");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.OptionPollPersonnalise", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Etape", "Etape")
                        .WithMany("Options")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etape");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Participant", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Board", "Board")
                        .WithMany("Participants")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("AreaPath")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Participant", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Colonne", "Colonne")
                        .WithMany()
                        .HasForeignKey("ColonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Etape", "Etape")
                        .WithMany("PostIts")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Colonne");

                    b.Navigation("Etape");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.RappelEnvoye", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Equipe", "Equipe")
                        .WithMany()
                        .HasForeignKey("AreaPath")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipe");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ReponseMeteoEquipe", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Etape", "Etape")
                        .WithMany("ReponsesMeteo")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etape");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.ReponsePollPersonnalise", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Etape", "Etape")
                        .WithMany("Reponses")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.OptionPollPersonnalise", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etape");

                    b.Navigation("Option");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Vote", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.Participant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScrumMaster.Api.Models.PostIt", "PostIt")
                        .WithMany("Votes")
                        .HasForeignKey("PostItId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("PostIt");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.VoteUtilite", b =>
                {
                    b.HasOne("ScrumMaster.Api.Models.PollUtilite", "Poll")
                        .WithMany("Votes")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Board", b =>
                {
                    b.Navigation("Etapes");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Equipe", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Etape", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("PostIts");

                    b.Navigation("Reponses");

                    b.Navigation("ReponsesMeteo");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PollUtilite", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.PostIt", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("ScrumMaster.Api.Models.Theme", b =>
                {
                    b.Navigation("Colonnes");
                });
#pragma warning restore 612, 618
        }
    }
}
