apiVersion: v1
kind: Service
metadata:
  name: scrummaster-frontend
  namespace: scrummaster
spec:
  selector:
    app.kubernetes.io/name: scrummaster-frontend
  ports:
    - port: 80
      targetPort: 8080
